### PR TITLE
Serialize errors with cause

### LINKED ISSUE #94: Explicitly check `cause` property on `Error` instances
The current error serializer only walks enumerable properties using a `for..in` loop. The downside to this is that vanilla errors with their `cause` property set are not enumerable by default.  I don't know if it's spec related or just specific to V8's implementation, but it's a bit wonky/unexpected nonetheless.

This means if you have the following code, the `cause` property won't actually be logged/printed.  It will only log the very first/top-level error.

```js
fastify.get('/throw', async (req, res) => {
  throw new Error('first cool error', {
    cause: new Error('second boring error', {
      cause: new Error('third awesome error'),
    }),
  });
});
```

Here's what node's inspector prints:

```
Uncaught [Error: first cool error] {
  [cause]: Error: second boring error
      at REPL5:2:12
      at Script.runInThisContext (node:vm:129:12)
      ... 7 lines matching cause stack trace ...
      at REPLServer.[_line] [as _line] (node:internal/readline/interface:879:18) {
    [cause]: Error: third awesome error
        at REPL5:3:14
        at Script.runInThisContext (node:vm:129:12)
        at REPLServer.defaultEval (node:repl:566:29)
        at bound (node:domain:421:15)
        at REPLServer.runBound [as eval] (node:domain:432:12)
        at REPLServer.onLine (node:repl:893:10)
        at REPLServer.emit (node:events:539:35)
        at REPLServer.emit (node:domain:475:12)
        at REPLServer.[_onLine] [as _onLine] (node:internal/readline/interface:418:12)
        at REPLServer.[_line] [as _line] (node:internal/readline/interface:879:18)
  }
}
```

Would people be open to a PR that explicitly checks for a `cause` key alongside the existing `for..in` check?  Are there other ways to achieve this?  It seems like this would be an expected/sane default, but perhaps there are downsides to doing this or was previously not done intentionally?

Thanks.

### PR DESCRIPTION
**Pull request by hypesystem**
Related to #76 and #78 which add serialization of `cause` into error messages.

This PR fixes #94 by making sure the chain of causes found in `err.cause` is serialized in full, bringing the final serialized result closer to what is printed by other serializers (e.g. those in the Node.js CLI and browser consoles).

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@voxpelli could you take a look?

**Comment by mcollina** [comment]
CI is failing

**Comment by hypesystem** [comment]
It seems that my assumption (comment) "message serialization already walks cause-chain" is only true in Node.js 16 for some reason? (I am running 16 locally, too, so it might be...) https://github.com/pinojs/pino-std-serializers/pull/105/files#diff-a6ff895a4ce70729791324c8118f43cffada5a9e9cfe42ea1df4a18707f2c430R207

This is odd to me, because it looks like the same functionality should be happening. Could it be that earlier Node.js versions don't support the `cause` key in options?

**Comment by hypesystem** [comment]
Oh yes, looking at it now what fails is the following lines:

```
t.equal(serialized.message, 'bar: foo') // message serialization already walks cause-chain
t.ok(serialized.cause)
t.equal(serialized.cause.type, 'Error')
```

I'll try to look at other tests to see if similar things are handled there.

**Comment by hypesystem** [comment]
In the other tests (of cause serialization into the error message) the `.cause` field is set manually on the Error, instead of using the options object: https://github.com/pinojs/pino-std-serializers/blob/master/test/err.test.js#L51-L53

This could be an approach, of course, but it kind of obscures what the case we are trying to support is... Open to input on how to approach this :smile:

**Comment by hypesystem** [comment]
Fixed :smile:

File: lib/err.js [hunk 1]
```diff
@@ -60,6 +65,10 @@ function errSerializer (err) {
     _err.aggregateErrors = err.errors.map(err => errSerializer(err))
   }
 
+  if (err.cause) {
+    _err.cause = errSerializer(err.cause)
+  }
```
Comment (jsumners) [inline lib/err.js:70]: Does this account for nested causes?

```js
const err = Error('foo', {
  cause: Error('bar', { cause: Error('baz') }
})
```

Comment (hypesystem) [reply lib/err.js:70]: Yes, it calls `errSerializer` recursively, which performs the same check on each nested error.

I can expand the test to make it clearer if you want?

Comment (jsumners) [reply lib/err.js:70]: Yes, please.

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by voxpelli** [comment]
Um, so this now means that apart from the `.stack` getting all of the cause stacks appended and `.message` getting all of the cause messages appended we're now also doing that for each cause in itself?

So we're basically having two systems for serializing the causes at once?

I would say that either we walk the cause chain as this PR did, or we summarize the cause chain through the `.stack` and the `.message` as I did in #78.

Never do the both at once and especially never do the both recursively?

Sorry for not responding earlier :/

**Comment by hypesystem** [comment]
@voxpelli I agree, and raised the issue here, too: https://github.com/pinojs/pino-std-serializers/issues/94#issuecomment-1150367453

**Comment by voxpelli** [comment]
And in https://github.com/pinojs/pino-std-serializers/pull/78/files#diff-71c187d84f435004e68161a25e470d823f4de310a1d39b531cc02a90f3730149R56 we specifically opted out causes from recursion:

```javascript
if (val instanceof Error && key !== 'cause') {
  /* eslint-disable no-prototype-builtins */
  if (!val.hasOwnProperty(seen)) {
```

I think it should be rewritten as:


```javascript
if (val instanceof Error) {
  /* eslint-disable no-prototype-builtins */
  if (key !== 'cause' && !val.hasOwnProperty(seen)) {
```

That way it will exclude all `Error` causes from serialization, as intended, but keeping other causes

**Comment by hypesystem** [comment]
I'm not sure I understand the explicit opting out of recursing over `Error`s? Could you elaborate on that @voxpelli

**Comment by voxpelli** [comment]
Let's discuss it in #110
